name: "[CI] Test"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

env:
  CI: 1
  SIMPLECOV: 1
  NODE_VERSION: 18.17.1
  RUBY_VERSION: 3.3.10
  DISPLAY: ":99"
  RUBYOPT: '-W:no-deprecated'
  RAILS_ENV: test
  NODE_ENV: test
  DISABLE_SPRING: 1

jobs:
  matrix-config:
    name: Generate matrix config
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(cat .github/test-env-configs.json | jq -c .)" >> $GITHUB_OUTPUT

  setup:
    name: Setup test app
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - run: |
          sudo apt-get update; sudo apt-get -f install imagemagick

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: bundle exec rake test_app
        name: Create test app

      - name: Cache test app
        uses: actions/cache/save@v4
        with:
          path: spec/decidim_dummy_app
          key: test-app-${{ github.sha }}

  test-report:
    name: Tests - ${{ matrix.env-config }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [matrix-config, setup]
    strategy:
      matrix:
        include: ${{ fromJson(needs.matrix-config.outputs.matrix) }}
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore test app cache
        uses: actions/cache/restore@v4
        with:
          path: spec/decidim_dummy_app
          key: test-app-${{ github.sha }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 126.0.6478.182

      - name: Remove Chrome
        run: sudo apt remove google-chrome-stable

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 126.0.6478.182

      - name: Set environment variables from config
        run: |
          cat .github/test-env-configs.json | jq -r --arg config "${{ matrix.env-config }}" '.[] | select(.["env-config"] == $config) | to_entries | .[] | select(.key != "env-config") | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - run: bundle exec rspec spec
        name: RSpec

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: openpoke/decidim-module-pokecode

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test logs
          path: ./spec/decidim_dummy_app/log/test.log
          if-no-files-found: ignore